version: "3.5"

# networks:
#     flipinet:
#         external:
#             name: flipinet

services:
    app:
        image: "jcrecio/flipi-datafetcher:latest"
        ports:
            - "9999:9999"
        networks:
            - public
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
networks:
    public:
        external: 
            name: public