version: "3.5"

networks:
    overnet:
        external:
            name: overnet

services:
    app:
        image: "jcrecio/flipi-datafetcher:latest"
        ports:
            - "9999:9999"
        networks:
            - overnet
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip