version: "3.3"
services:
    app:
        image: "jcrecio/flipi-datafetcher:latest"
        ports:
            - "9999:9999"
        networks:
            - appnet
networks:
    appnet:
        driver: overlay