version: "3.5"

networks:
    flipinet:
        external:
            name: flipinet

services:
    app:
        image: "jcrecio/flipi-datafetcher:latest"
        ports:
            - "9999:9999"
        networks:
            - flipinet